---

- name: "Install kube-lego"
  command: kubectl apply -f -
  args:
    stdin: "{{ item }}"
  with_items:
    - "{{ lookup('template', 'rbac.yml.j2') }}"
    - "{{ lookup('template', 'configmap.yml.j2') }}"
    - "{{ lookup('template', 'deployment.yml.j2') }}"

# vim: set ts=2 sw=2:
